export const WISH_TEXT = [
  "Today is...",
  "as lovely as always",
  "but you realize",
  "another year has flown by",
  "in the blink of an eye",
  "Yet",
  "Do you know..?",
  "today is special",
  "so special to you",
  "that's why",
  "Let's make it...",
  "the best celebration ever",
  "and let me share...",
  "a piece of my happiness with you",
  "I made all this...",
  "as a birthday gift for you",
  "I cherish our bond",
  "thanks for everything",
  "I wish you the best",
  "May your life be at ease",
  "May all your dreams come true",
  "Remember",
  "your ambitions",
  "you are a free bird...",
  "flying in the blue sky",
  "Now things are changing...",
  "the real story of your life",
  "is just beginning",
  "truly",
  "but...",
  "don't worry",
  "because...",
  "God is with you",
  "and",
  "so am I ❤️",
  "This year will be better",
  "and I hope",
  "we'll find...",
  "the true meaning of life together",
  "keep your spirits high",
  "enjoy every moment...",
  "you experience today",
  "fill it with your brightest smile",
  "and make it the best memory",
  "finally...",
  "I wish you once more",
  "a very Happy Birthday 🥳",
  "- from Badhir Meow 🐱",
  "Also...",
  "Don't forget my (😘)",
  "Okay Byeeeee...!!",
];

export const IMAGES = [
  "https://res.cloudinary.com/randomwave45/image/upload/v1720361202/IMG_20161204_144046507_fbsown.jpg",
  "https://res.cloudinary.com/randomwave45/image/upload/v1720361202/IMG_20150905_181921656_psnsha.jpg",
  "https://res.cloudinary.com/randomwave45/image/upload/v1720361544/IMG-20181214-WA0002_hzvead.jpg",
  "https://res.cloudinary.com/randomwave45/image/upload/v1720361201/IMG_20160915_112123735_v6hmgj.jpg",
  "https://res.cloudinary.com/randomwave45/image/upload/v1720361202/IMG_20160908_095848374_vopjnb.jpg",
];
