export const WISH_TEXT = [
  "Today is...",
  "as beautiful as other days",
  "but you realize",
  "another year has gone",
  "in a blink of the eyes",
  "However",
  "Do you know..?",
  "today is just special",
  "so special to you",
  "that's why",
  "Let's make it...",
  "the best celebration ever",
  "and let me share...",
  "a piece of happiness to you",
  "I made all this...",
  "as a birthday present to you",
  "thanks for the bond that we made",
  "thanks for everything",
  "I wish you all the best",
  "May your life be at ease",
  "May all your wishes come true",
  "Remember",
  "your ambitions",
  "you live as a free bird...",
  "flying in the blue sky",
  "Now things are different...",
  "real story of your life",
  "is just about to begin",
  "indeed..",
  "but...",
  "don't worry",
  "because...",
  "God has your back",
  "and",
  "of course me too 😂 ❤️",
  "This year will be better",
  "and I hope",
  "we'll find...",
  "true meaning to life along the way",
  "keep your spirit up",
  "enjoy every single moment...",
  "that you experience today",
  "fill it with your most beautiful smile",
  "and make it the best memory..",
  "lastly...",
  "I'd like to wish you one more time",
  "a very Happy Birthday 🥳",
  "- from Badhir Meow 🐱",
  "Also...",
  "Don't forget my (😘)",
  "Okay Byeeeee...!!",
];

export const IMAGES = [
  "https://res.cloudinary.com/randomwave45/image/upload/v1720361202/IMG_20161204_144046507_fbsown.jpg",
  "https://res.cloudinary.com/randomwave45/image/upload/v1720361202/IMG_20150905_181921656_psnsha.jpg",
  "https://res.cloudinary.com/randomwave45/image/upload/v1720361544/IMG-20181214-WA0002_hzvead.jpg",
  "https://res.cloudinary.com/randomwave45/image/upload/v1720361201/IMG_20160915_112123735_v6hmgj.jpg",
  "https://res.cloudinary.com/randomwave45/image/upload/v1720361202/IMG_20160908_095848374_vopjnb.jpg",
];
